/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    alias(libs.plugins.version.code.kotlin.library)
}

features {
    unitTests = true
}

dependencies {
}